### PR TITLE
Pansharpened mosaic selection

### PR DESCRIPTION
**Pull request by bakkerbakker**
Adding functionality to get mul-pan pairs in the mosaic query script using the `--require-pan` flag.

### CODE REVIEW

**Comment by bakkerbakker** [comment]
We will have to check `pgc_mosaic.py` to make see if we need to port any of the functionality over there and then add a pansharpening option to `image-mosaic-scripts` for batch processing.

**Comment by bakkerbakker** [comment]
With the addition in the commit [here](https://github.com/PolarGeospatialCenter/imagery_utils/pull/88/commits/3946f1dada0e446dfcbe877dd5e2e2998fa78002), the batch processing scripts in `image-mosaic-scrips` should work as long as the config includes the pansharpen flag. Once QC is complete, we can test the mosaic part of the process, but I don't think this branch will need any more additions. Will leave in draft form until then.

Also, including a bug fix for multi-task pansharpen jobs that used the `--resolution` flag that recursively made the output resolution larger when submitting multiple tasks within the same slurm job.

**Comment by bakkerbakker** [comment]
Corresponds to changes made to `image-mosaic-scripts` in the PR here: https://github.umn.edu/pgc/image-mosaic-scripts/pull/7

**Review by bakkerbakker — COMMENTED** [review]
@clairecporter this is the fix for the recursive downsampling of the pansharpened outputs when passing in a value to the `-r` flag and running multiple tasks per job.

**Comment by clairecporter** [comment]
Did you run the test suit to make sure these changes did not break something else?  In the same vein, can you add a test to run through this functionality?  Let me know if there's a blocker I can help with on that.

**Comment by bakkerbakker** [comment]
@clairecporter I've run these changes through the full mosaic production process but I have not run the tests or updated the test suite. I'll probably need a little help adding unit tests for this update.

**Review by clairecporter — APPROVED** [review]
This the passes the working tests.  I repaired the pansharpening tests while I was at it.

**Comment by clairecporter** [comment]
The mosaic test are not yet repaired.  Do you want to wait until I get them fixed up?

**Comment by clairecporter** [comment]
With these commits, all the tests work.  Some are skipped for the moment, but we'll revisit those when we switch to pytest.  If you approve of the changes, you can roll these into main.

**Pull request merged**
